In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
arr1=np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr2=np.array([0.1,0.2,0.3])
arr2

array([0.1, 0.2, 0.3])

In [5]:
arr3=np.array(['a','b','c'])
arr2

array([0.1, 0.2, 0.3])

In [6]:
arr4=np.array([1,2,'a','b',0.1,0.2])
arr3 #정수,문자,실수가 함께있는데 모두가 문자열로 바뀜.자동으로 형변환을 시킴.

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
arr5=np.array([1,2,0.3,0.4])
arr4 #실수를 넣어서 형변환이 됨.

array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [9]:
l1=[[1,0.1,'a','b',[2,3,4]]]
l1#array는 다차원이라 불려야함

[[1, 0.1, 'a', 'b', [2, 3, 4]]]

# array의 타입

In [10]:
arr1.dtype

dtype('int32')

In [11]:
arr2.dtype

dtype('float64')

In [12]:
arr3.dtype #unicode,1가지 숫자

dtype('<U1')

In [13]:
arr4.dtype #unicode,11가지 모듈

dtype('<U11')

In [14]:
arr5.dtype

dtype('float64')

In [16]:
arr6=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr6.dtype

dtype('int32')

# shape

In [17]:
arr5.shape

(4,)

In [18]:
arr6.shape

(3, 3)

# arange,linspace

In [19]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr2=np.arange(3,13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
arr3=np.arange(5.0)
arr3

array([0., 1., 2., 3., 4.])

In [25]:
arr4=np.arange(3,100,3.0)
arr4

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78.,
       81., 84., 87., 90., 93., 96., 99.])

# linspace

In [27]:
arr1=np.linspace(-5,5,10)
arr1

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

## reshape(배열의 형태 변환)

In [28]:
arr1=np.arange(36.0)

In [29]:
arr1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [30]:
arr1.shape

(36,)

In [33]:
arr2=arr1.reshape(12,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.]])

In [34]:
arr2.shape

(12, 3)

In [35]:
arr3=arr1.reshape(3,4,3)
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [39]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr.shape=[5,2]
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
#-1 shape
arr3.reshape(-1,12)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [43]:
arr3.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [44]:
arr3.reshape(4,-1,3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]],

       [[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

### astype-배열의 dtype변환

In [45]:
arr1=np.arange(5)
arr2=np.arange(0.0,0.5,0.1)

In [46]:
arr1,arr2

(array([0, 1, 2, 3, 4]), array([0. , 0.1, 0.2, 0.3, 0.4]))

In [47]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [49]:
#int->float
print(arr1.astype(float))
print(arr1.astype(np.float64))

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]


## float=>char

In [52]:
print(arr2.astype(str))
print(arr2.astype(np.str))

['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']
['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']


# rand

In [54]:
np.random.rand(5)

array([0.53619804, 0.68781405, 0.73107091, 0.20928548, 0.06647185])

In [55]:
np.random.rand(3,3)

array([[0.29949599, 0.10165687, 0.42959135],
       [0.72184336, 0.29037703, 0.83585649],
       [0.17987131, 0.57226851, 0.75887906]])

In [56]:
np.random.rand(2,2,2)

array([[[0.34373552, 0.89074657],
        [0.38126661, 0.44475441]],

       [[0.69452771, 0.90450425],
        [0.17771998, 0.12903715]]])

In [57]:
np.random.randint(-5,3,(3,3))

array([[-4, -1,  2],
       [-2, -2, -5],
       [-1,  1, -4]])

In [60]:
np.random.randn(2,5)

array([[ 0.75997971,  0.95451223, -1.00832253,  2.57924187,  0.24098789],
       [ 1.00451742, -0.33247001, -0.28089357, -0.303731  , -1.6448826 ]])

# array의 indexing,slicing

In [62]:
arr1=np.arange(0,100,10.0)
arr1

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [63]:
arr1[0],arr1[-1],arr1[5]

(0.0, 90.0, 50.0)

In [64]:
arr1[:],arr1[4:],arr1[1:]

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]),
 array([40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40., 50., 60., 70., 80., 90.]))

## n-dim Array indexing,Slicing

In [69]:
#2차원 배열:0~23,(8,3)배열로 만들기
arr2=np.arange(24.0).reshape(8,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [70]:
arr2[0]

array([0., 1., 2.])

In [71]:
arr2[4]

array([12., 13., 14.])

In [73]:
print(arr2[3][1]) #성능이 조금 느림:연산을 2번해서 그런거임.

10.0


In [74]:
print(arr2[3,1])

10.0


In [75]:
print(arr2[3,1:])

[10. 11.]


In [76]:
print(arr2[3:,1:])

[[10. 11.]
 [13. 14.]
 [16. 17.]
 [19. 20.]
 [22. 23.]]


In [77]:
print(arr2[::2,:])

[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]
 [18. 19. 20.]]


In [79]:
arr2[[0,5,3]]

array([[ 0.,  1.,  2.],
       [15., 16., 17.],
       [ 9., 10., 11.]])

In [81]:
print(arr2[[0,5,3],[1]])

[ 1. 16. 10.]


In [83]:
arr2[arr2>10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [84]:
arr2>10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [85]:
arr2[arr2%2==1]

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

### numpy의 상수

In [86]:
arr=np.array([1,2,3,np.nan,np.inf,-np.inf])
print('dtype:',arr.dtype)
arr

dtype: float64


array([  1.,   2.,   3.,  nan,  inf, -inf])

## arr의 연산

In [88]:
arr1=np.arange(0,10,1)
arr2=np.arange(1,0,-0.1)
arr1,arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [89]:
#array와 scalar 연산
arr1+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr1+[1,1,1,1,1,1,1,1,1,1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
print(arr1-1)
print(arr1*10)
print(arr1/10)
print(arr1**2)
print(arr1%2)

[-1  0  1  2  3  4  5  6  7  8]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [92]:
arr1+arr2

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [93]:
arr1>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [94]:
arr1>arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# 행렬

In [95]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [97]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 단위행렬

In [98]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [99]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [101]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 통계를 위한 연산

In [106]:
arr1=np.arange(1,11.0).reshape(5,2)
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [107]:
arr1.sum()

55.0

In [109]:
arr1.sum(axis=1)#0은 열,1은 행

array([ 3.,  7., 11., 15., 19.])

In [110]:
arr1.mean()

5.5

In [111]:
arr1.mean(axis=1)#0은 열,1은 행

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [113]:
arr1.var(axis=1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

In [114]:
arr1.var(axis=0)

array([8., 8.])

In [115]:
arr1.var()

8.25

In [116]:
arr1.std()

2.8722813232690143

In [117]:
arr1.std(axis=0)

array([2.82842712, 2.82842712])

In [118]:
arr1.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [119]:
np.sqrt(arr1.var(axis=1))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [122]:
np.log(arr1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [123]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

In [124]:
np.exp(arr1).dtype

dtype('float64')

In [125]:
print(arr1.min())
print(arr1.min(axis=0))
print(arr1.min(axis=1))

1.0
[1. 2.]
[1. 3. 5. 7. 9.]


In [126]:
print(arr1.max())
print(arr1.max(axis=0))
print(arr1.max(axis=1))

10.0
[ 9. 10.]
[ 2.  4.  6.  8. 10.]


In [130]:
print(arr1.cumsum())
print(arr1.cumsum(axis=0))
print(arr1.cumsum(axis=1))

[ 1.  3.  6. 10. 15. 21. 28. 36. 45. 55.]
[[ 1.  2.]
 [ 4.  6.]
 [ 9. 12.]
 [16. 20.]
 [25. 30.]]
[[ 1.  3.]
 [ 3.  7.]
 [ 5. 11.]
 [ 7. 15.]
 [ 9. 19.]]


In [129]:
print(arr1.cumprod())
print(arr1.cumprod(axis=0))
print(arr1.cumprod(axis=1))

[1.0000e+00 2.0000e+00 6.0000e+00 2.4000e+01 1.2000e+02 7.2000e+02
 5.0400e+03 4.0320e+04 3.6288e+05 3.6288e+06]
[[1.00e+00 2.00e+00]
 [3.00e+00 8.00e+00]
 [1.50e+01 4.80e+01]
 [1.05e+02 3.84e+02]
 [9.45e+02 3.84e+03]]
[[ 1.  2.]
 [ 3. 12.]
 [ 5. 30.]
 [ 7. 56.]
 [ 9. 90.]]


In [136]:
arr1=np.arange(1,7).astype('float64').reshape(2,3)
arr2=np.arange(6,0,-1.0).astype('float64').reshape(3,2)
arr1,arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[6., 5.],
        [4., 3.],
        [2., 1.]]))

In [139]:
arr1.shape,arr2.shape

((2, 3), (3, 2))

In [141]:
arr1@arr2

array([[20., 14.],
       [56., 41.]])

In [142]:
np.matmul(arr1,arr2)

array([[20., 14.],
       [56., 41.]])

In [143]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [150]:
arr3=np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [151]:
arr1.shape,arr3.shape

((2, 3), (2, 3))

In [152]:
arr3.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [153]:
arr3.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [154]:
arr1.dot(arr3.T)

array([[ 8., 26.],
       [17., 62.]])

# 역행렬

In [155]:
arr1=np.arange(1,5).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [156]:
arr2=np.linalg.inv(arr1)
arr2

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [157]:
arr1.dot(arr2)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [159]:
arr1=np.arange(4).reshape(2,2)
arr2=np.arange(0,40,10).reshape(2,2)
arr1,arr2

(array([[0, 1],
        [2, 3]]),
 array([[ 0, 10],
        [20, 30]]))

In [163]:
np.concatenate((arr1,arr2),axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [20, 30]])

In [164]:
np.concatenate((arr1,arr2),axis=1)

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

# 연습문제

In [167]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [170]:
arr[4:6]=1

In [171]:
arr.reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [172]:
arr1=np.arange(10,30,2)
arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [175]:
a=np.arange(1,2,0.1)
a

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [176]:
arr1+a,arr1*a,arr1-a,arr1/a

(array([11. , 13.1, 15.2, 17.3, 19.4, 21.5, 23.6, 25.7, 27.8, 29.9]),
 array([10. , 13.2, 16.8, 20.8, 25.2, 30. , 35.2, 40.8, 46.8, 53.2]),
 array([ 9. , 10.9, 12.8, 14.7, 16.6, 18.5, 20.4, 22.3, 24.2, 26.1]),
 array([10.        , 10.90909091, 11.66666667, 12.30769231, 12.85714286,
        13.33333333, 13.75      , 14.11764706, 14.44444444, 14.73684211]))

In [178]:
arr2=np.arange(1,100,10)
arr2

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [179]:
print(arr2.sum())
print(arr2.mean())
print(arr2.var())
print(arr2.std())
print(arr2.min())
print(arr2.max())
print(arr2.cumsum())
print(arr2.cumprod())

460
46.0
825.0
28.722813232690143
1
91
[  1  12  33  64 105 156 217 288 369 460]
[          1          11         231        7161      293601    14973651
   913392711   426373041   176477953 -1120375461]


In [235]:
np.random.seed(42)

In [237]:
arr1=np.random.rand(3,3)
arr2=arr1*10
arr2

array([[7.08072578, 0.20584494, 9.69909852],
       [8.32442641, 2.12339111, 1.81824967],
       [1.8340451 , 3.04242243, 5.24756432]])

In [238]:
np.random.randint(0,10,(3,3))

array([[8, 0, 9],
       [2, 6, 3],
       [8, 2, 4]])

## 6번~7번문제

In [251]:
arr1=np.linspace(-1000,1000,5)
arr1=arr1.reshape(5,-1)
arr2=np.linspace(0,10,5)
arr2=arr2.reshape(5,-1)
arr3=np.concatenate((arr1,arr2),axis=1)
arr3=arr3.reshape(5,2)
arr3

array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [252]:
arr1.std(),arr2.std()

(707.1067811865476, 3.5355339059327378)

In [254]:
arr4=(arr3-arr3.mean(axis=0))/arr3.std(axis=0)
arr4
arr4.mean(),arr4.std()

(0.0, 0.9999999999999999)

In [226]:
x.mean(axis=0),x.std(axis=0)

(array([4. , 2.6]), array([1.78885438, 2.05912603]))

In [227]:
(x-x.mean(axis=0))/x.std(axis=0)

array([[-1.11803399, -0.77702869],
       [-0.55901699, -0.77702869],
       [ 0.55901699, -0.77702869],
       [ 1.67705098,  0.6799001 ],
       [-0.55901699,  1.65118597]])

In [228]:
a=(x-x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))
a

array([[0. , 0. ],
       [0.2, 0. ],
       [0.6, 0. ],
       [1. , 0.6],
       [0.2, 1. ]])