In [1]:
import tensorflow as tf

In [2]:
import keras 

In [3]:
from tensorflow.keras.models import Sequential #모델의 구조
from tensorflow.keras.layers import Dense

import numpy as np
np.random.seed(3)
tf.random.set_seed(3)

In [4]:
Data_set=np.loadtxt('./data/ThoraricSurgery.csv',delimiter=',')

In [7]:
X=Data_set[:,:17]#속성
Y=Data_set[:,17]#클래스
#텐서플로 2점대는 캐라스가 포함되어있다.
#텐서플로를 쉽게 사용할 수 있게 하는게 케라스.
#텐서플로는 비행기 케라스는 파일럿에 해당
model=Sequential()
model.add(Dense(30,input_dim=17,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])
model.fit(X,Y,epochs=100,batch_size=10)
print('\n Accuracy: %.4f'%(model.evaluate(X,Y)[1]))#loss,accuracy

Epoch 1/100
47/47 [==============================] - 0s 572us/step - loss: 0.8508 - accuracy: 0.1489
Epoch 2/100
47/47 [==============================] - 0s 530us/step - loss: 0.8111 - accuracy: 0.1809
Epoch 3/100
47/47 [==============================] - 0s 626us/step - loss: 0.7332 - accuracy: 0.2638
Epoch 4/100
47/47 [==============================] - 0s 613us/step - loss: 0.6684 - accuracy: 0.3255
Epoch 5/100
47/47 [==============================] - 0s 593us/step - loss: 0.2778 - accuracy: 0.7128
Epoch 6/100
47/47 [==============================] - 0s 597us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 7/100
47/47 [==============================] - 0s 590us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 8/100
47/47 [==============================] - 0s 615us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 9/100
47/47 [==============================] - 0s 595us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 10/100
47/47 [==============================] - 0s 613us/step - loss: 0.1489 - accura

47/47 [==============================] - 0s 585us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 82/100
47/47 [==============================] - 0s 618us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 83/100
47/47 [==============================] - 0s 586us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 84/100
47/47 [==============================] - 0s 577us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 85/100
47/47 [==============================] - 0s 595us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 86/100
47/47 [==============================] - 0s 564us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 87/100
47/47 [==============================] - 0s 583us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 88/100
47/47 [==============================] - 0s 572us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 89/100
47/47 [==============================] - 0s 564us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 90/100
47/47 [==============================] - 0s 574us/step - loss: 0.1489 - accuracy: 

# Numpy

C로 구현,빠른 수치계산을 위한 structured Array 제공,BLAS/LAPACK 기반

동일 타입의 원소,메모리 최적화,계산 속도 향상 등....

In [9]:
ar=np.array([0,1,2,3,4,5,6,7,8,9])
ar,type(ar)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [10]:
data=[0,1,2,3,4,5,6,7,8,9] #벡터화 연산을 지원하는게 배열 객체

In [11]:
answer=[]
for d in data:
    answer.append(2*d)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
x=np.array(data)
x,2*x

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]))

In [13]:
a=np.array([1,2,3])
b=np.array([10,20,30])

In [14]:
2*a+b

array([12, 24, 36])

In [15]:
a==2

array([False,  True, False])

In [16]:
b>10

array([False,  True,  True])

In [17]:
(a==2)&(b>10)

array([False,  True, False])

# 2차원 배열

In [18]:
c=np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
len(c),len(c[0]) #행과 열의 개수

(2, 3)

In [20]:
a=np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [21]:
d=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

In [22]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [23]:
len(d),len(d[0]),len(d[0][0])

(2, 3, 4)

In [24]:
a=np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [25]:
print(c.ndim)
print(c.shape)

2
(2, 3)


In [26]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [27]:
a=np.array([0,1,2,3,4])
a[2]

2

In [32]:
a=np.array([[0,1,2],[3,4,5]])

In [37]:
a[0,1]

1

In [36]:
a[-1,-1]

5

In [38]:
a=np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
a[0,:]

array([0, 1, 2, 3])

In [40]:
a[:,1]

array([1, 5])

In [41]:
a[1,1:]

array([5, 6, 7])

In [42]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [43]:
m=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [47]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
m[1,2]

7

In [45]:
m[-1,-1]

14

In [46]:
m[1,1:3]

array([6, 7])

In [48]:
m[1:,2]

array([ 7, 12])

In [49]:
m[:2,-2:]

array([[3, 4],
       [8, 9]])

In [50]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
idx=np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([0, 2, 4, 6, 8])

In [51]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [52]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b=a[idx]
b

array([0, 2, 4, 6, 8])

In [54]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [55]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [56]:
a=np.array([11,22,33,44,55,66,77,88,99])
idx=np.array([0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [57]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
a[:,[True,False,False,True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [59]:
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [64]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [61]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [65]:
x[(x%3)+((x-1)%4==1)==1]

array([ 1,  4,  6,  7, 13, 16, 18, 19])

In [66]:
x=np.array([1,2,3])
x.dtype

dtype('int32')

In [67]:
x=np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [68]:
x=np.array([1,2,3.0])
x.dtype

dtype('float64')

In [69]:
x=np.array([1,2,3],dtype='f')
x.dtype

dtype('float32')

In [70]:
x[0]+x[1]

3.0

In [71]:
x

array([1., 2., 3.], dtype=float32)

In [72]:
x=np.array([1,2,3],dtype='U')
x.dtype

dtype('<U1')

In [73]:
x

array(['1', '2', '3'], dtype='<U1')

In [74]:
np.array([0,1,-1,0])/np.array([1,0,0,0]) #요소끼리 나눔

<ipython-input-74-dc768ac6b521>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
<ipython-input-74-dc768ac6b521>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [75]:
np.log(0)

<ipython-input-75-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [76]:
np.exp(-np.inf)

0.0

In [77]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.zeros((2,3),dtype='i')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [80]:
np.zeros((5,2),dtype='i')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [81]:
d=np.zeros(5,dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [82]:
d[0]='abc'
d[1]='abcd'
d[2]='ABCDE'
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [83]:
e=np.ones((2,3,4),dtype='i8') #8byte->int64
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [87]:
#다른 배열과 같은 크기의 생성:ones_like,zeros_like
b=np.array([[0.,0.,0.],[0.,0.,0.]])
f=np.ones_like(b,dtype='f')
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [84]:
g=np.empty((4,3))
g

array([[1.33030234e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.37673983e-057],
       [4.74585666e+174, 1.65556495e-047, 1.29201521e+161],
       [4.50654030e-033, 1.46582766e-075, 9.20846829e+169]])

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [91]:
np.linspace(0,100,5)#섢형구간 혹은 로그 구간을 지정한 구간의 수만큼 분할

array([  0.,  25.,  50.,  75., 100.])

In [92]:
np.logspace(0.1,1,10) #1과 10 10개의 점 생성
#10의 제곱수인 10^a와 10^b 사이에 있는 n개의 점 생성

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [93]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [95]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
a.reshape(2,2,-1)#나머지 3개는 알아서해라.

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [100]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [101]:
a,a.flatten()

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [102]:
a.ravel() #1차원으로 펼치기

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [104]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a=np.arange(5)
a.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [106]:
a.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [107]:
print(a)

[0 1 2 3 4]


In [108]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [109]:
y=a[:,np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [110]:
y.shape

(5, 1)

In [112]:
a1=np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [113]:
a2=np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [115]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [116]:
a2=np.zeros((3,3))
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.vstack([a1,a2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [118]:
c1=np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [119]:
c2=np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [120]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [121]:
a=np.array([[0,1,2],[3,4,5]])
np.tile(a,2) 

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [122]:
np.tile(a,(3,2))#밑의 3번 옆에 2번 반복

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [123]:
x=np.arange(3)
y=np.arange(5)

In [124]:
X,Y=np.meshgrid(x,y)

In [125]:
X #세로로 쌓음

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [126]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [127]:
x=np.arange(1,10001)
y=np.arange(10001,20001)
x

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [128]:
%%time
z=np.zeros_like(x)
for i in range(10000):
    z[i]=x[i]+y[i]

Wall time: 3.99 ms


In [129]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [130]:
z[:]

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [131]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [133]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [135]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [136]:
x+1

array([1, 2, 3, 4, 5])

In [137]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [138]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[10,100,1000],[10000,100000,1000000]])

In [141]:
x*y

array([[     10,     200,    3000],
       [  40000,  500000, 6000000]])

In [143]:
np.dot(x,y.T)

array([[   3210, 3210000],
       [   6540, 6540000]])

In [145]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [146]:
np.sum(x)

10

In [147]:
x.sum()

10

In [148]:
x.min()

1

In [149]:
x.argmin()

0

In [150]:
x.argmax()

3

In [151]:
x=np.array([1,2,3,1])

In [152]:
x.mean()

1.75

In [154]:
np.median(x)

1.5

In [155]:
np.all([True,True,False])

False

In [156]:
np.any([True,True,False])

True

In [157]:
a=np.array([[4,3,5,7],[1,12,11,9],[2,15,1,14]])
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [158]:
a=np.array([[4,3,5,7],[1,12,11,9],[2,15,1,14]])
np.sort(a,axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [160]:
a.sort(axis=1)#한번 실행하면 자기자신이 바뀜
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [161]:
a=np.array([42,38,12,25])
j=np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [162]:
a[j]

array([12, 25, 38, 42])

In [163]:
np.sort(a)

array([12, 25, 38, 42])

In [167]:
a=np.loadtxt('./data/ThoraricSurgery.csv',delimiter=',')
a

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [168]:
x1=np.array([1.1,2.2,3.1])
np.savetxt('./x1.txt',x1)

x2=np.array([1.1,2.2,3.1]).reshape(1,3)
np.savetxt('./x2.txt',x2)

x3=np.array([1.1,2.2,3.1]).reshape(3,1)
np.savetxt('./x3.txt',x3)

In [169]:
a=np.loadtxt('./x1.txt',delimiter=',')
a

array([1.1, 2.2, 3.1])